### ISSUE TITLE
Current included version of EPUBCheck is only 3.0.1

### ISSUE THREAD

**Issue by martinpub** [daisy/obi#180]
[Current EPUBCheck version available is v.4.2.4.](https://github.com/w3c/epubcheck/releases)

This may result in less valid EPUB 3 files than the user expects.

**Comment by avneeshsingh** [comment]
Obi supports EPUB 3.0, and we have intentionally not updated it to latest version, EPUB version 3.2. This is because EPUB 3 does not support audio-only books. The current EPUB implementation in Obi is a workaround for making it possible. But EPUB 3 is unsuitable for audio books. This is why we had decided to focus more on workflow advancements and improving DAISY export instead of updating EPUB 3 implementation.
DAISY 3 and DAISY 2.02 are the best formats for well structured audio books, therefore we will continue focus on these.
Just for information, Obi also provides reference implementation of new W3C audio books specification, it is another simple format for main stream publishers, but it also does not match the sophistication of DAISY specifications at this time. Therefore our main focus will remain on DAISY for now.
